---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    fabric8.io/git-commit: "9f00d7ef75a5d61c4e684ec908ccfbbad1aa0995"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
    fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=camel&var-version=1.0-SNAPSHOT"
  labels:
    provider: "fabric8"
    project: "camel"
    version: "1.0-SNAPSHOT"
    group: "br.com.sysmi.treinamento"
  name: "camel"
spec:
  replicas: 1
  selector:
    project: "camel"
    provider: "fabric8"
    group: "br.com.sysmi.treinamento"
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: "Rolling"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "9f00d7ef75a5d61c4e684ec908ccfbbad1aa0995"
        fabric8.io/iconUrl: "img/icons/camel.svg"
        fabric8.io/git-branch: "master"
        fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=camel&var-version=1.0-SNAPSHOT"
      labels:
        provider: "fabric8"
        project: "camel"
        version: "1.0-SNAPSHOT"
        group: "br.com.sysmi.treinamento"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "treinamento/camel:snapshot-181010-145122-0656"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 180
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.2"
        securityContext:
          privileged: false
  triggers:
  - type: "ConfigChange"
